// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("1.0.0")]
[assembly: AssemblyFileVersionAttribute("1.0.1")]
[assembly: AssemblyInformationalVersionAttribute("1.0.1-beta")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyVersion = "1.0.0";
        internal const System.String AssemblyFileVersion = "1.0.1";
        internal const System.String AssemblyInformationalVersion = "1.0.1-beta";
    }
}
